"""Test harness: a real PostgreSQL database, migrated by Alembic.

Two deliberate choices:

* The schema is built by running the **migrations**, not `Base.metadata.create_all`.
  The migration is the artifact that runs in production; a test suite that bypasses
  it cannot catch a migration that does not match the models.
* Everything goes through asyncpg — no psycopg dependency just to issue
  `CREATE DATABASE`. An AUTOCOMMIT engine on the maintenance database does that job.
"""

import asyncio
import os
from collections.abc import AsyncIterator
from pathlib import Path

import pytest
from alembic import command
from alembic.config import Config
from sqlalchemy import text
from sqlalchemy.exc import SQLAlchemyError
from sqlalchemy.ext.asyncio import AsyncEngine, AsyncSession, create_async_engine

REPO_ROOT = Path(__file__).resolve().parent.parent
TEST_DB_NAME = "fleetforge_test"
DEFAULT_DEV_URL = "postgresql+asyncpg://fleetforge:fleetforge@localhost:5433/fleetforge"


def database_url_for(db_name: str) -> str:
    """Return the configured dev/test URL with its database name replaced."""
    base = os.environ.get("TEST_DATABASE_URL") or os.environ.get("DATABASE_URL", DEFAULT_DEV_URL)
    head, _, _ = base.rpartition("/")
    return f"{head}/{db_name}"


TERMINATE_SQL = text(
    "SELECT pg_terminate_backend(pid) FROM pg_stat_activity "
    "WHERE datname = :db_name AND pid <> pg_backend_pid()"
)


async def drop_database(db_name: str, then_create: bool = False) -> None:
    """Drop `db_name` (optionally recreating it), evicting stragglers first.

    `DROP`/`CREATE DATABASE` cannot run inside a transaction and cannot take bind
    parameters, hence the AUTOCOMMIT engine and the quoted identifier. `db_name` is a
    module constant, never user input.
    """
    admin_engine = create_async_engine(
        database_url_for("postgres"), isolation_level="AUTOCOMMIT", pool_pre_ping=True
    )
    try:
        async with admin_engine.connect() as conn:
            await conn.execute(TERMINATE_SQL, {"db_name": db_name})
            await conn.exec_driver_sql(f'DROP DATABASE IF EXISTS "{db_name}"')
            if then_create:
                await conn.exec_driver_sql(f'CREATE DATABASE "{db_name}"')
    finally:
        await admin_engine.dispose()


async def recreate_database(db_name: str) -> None:
    """Drop and recreate `db_name`."""
    await drop_database(db_name, then_create=True)


def alembic_config() -> Config:
    """Alembic config pinned to the repo root, wherever pytest was invoked from."""
    cfg = Config(str(REPO_ROOT / "alembic.ini"))
    cfg.set_main_option("script_location", str(REPO_ROOT / "alembic"))
    return cfg


async def run_alembic(db_url: str, action: str = "upgrade", revision: str = "head") -> None:
    """Run an Alembic command against `db_url` in a worker thread.

    `alembic/env.py` calls `asyncio.run()`, which cannot be nested inside the running
    test loop — hence `to_thread`. `env.py` reads DATABASE_URL from the environment,
    so that is how the target database is selected.
    """
    runner = {"upgrade": command.upgrade, "downgrade": command.downgrade}[action]
    previous = os.environ.get("DATABASE_URL")
    os.environ["DATABASE_URL"] = db_url
    try:
        await asyncio.to_thread(runner, alembic_config(), revision)
    finally:
        if previous is None:
            os.environ.pop("DATABASE_URL", None)
        else:
            os.environ["DATABASE_URL"] = previous


async def run_alembic_check(db_url: str) -> None:
    """Run `alembic check` against `db_url`; raises AutogenerateDiffsDetected on drift."""
    previous = os.environ.get("DATABASE_URL")
    os.environ["DATABASE_URL"] = db_url
    try:
        await asyncio.to_thread(command.check, alembic_config())
    finally:
        if previous is None:
            os.environ.pop("DATABASE_URL", None)
        else:
            os.environ["DATABASE_URL"] = previous


@pytest.fixture(scope="session")
async def engine() -> AsyncIterator[AsyncEngine]:
    """Session-scoped engine bound to a freshly migrated `fleetforge_test`."""
    test_url = database_url_for(TEST_DB_NAME)
    try:
        await recreate_database(TEST_DB_NAME)
    except SQLAlchemyError as exc:  # pragma: no cover - environment problem, not a test failure
        pytest.exit(
            "Cannot reach PostgreSQL at "
            f"{database_url_for('postgres')}: {exc}\n"
            "Start the dev database first:  just db-up",
            returncode=1,
        )

    await run_alembic(test_url)

    test_engine = create_async_engine(test_url, pool_pre_ping=True)
    try:
        yield test_engine
    finally:
        await test_engine.dispose()
        await drop_database(TEST_DB_NAME)


@pytest.fixture
async def session(engine: AsyncEngine) -> AsyncIterator[AsyncSession]:
    """A session inside a transaction that is always rolled back.

    Tests never see each other's rows, and nothing needs cleaning up.
    """
    async with engine.connect() as connection:
        transaction = await connection.begin()
        async_session = AsyncSession(bind=connection, expire_on_commit=False)
        try:
            yield async_session
        finally:
            await async_session.close()
            if transaction.is_active:
                await transaction.rollback()
