"""Test harness: a real PostgreSQL database, migrated by Alembic.

Two deliberate choices:

* The schema is built by running the **migrations**, not `Base.metadata.create_all`.
  The migration is the artifact that runs in production; a test suite that bypasses
  it cannot catch a migration that does not match the models.
* Everything goes through asyncpg — no psycopg dependency just to issue
  `CREATE DATABASE`. An AUTOCOMMIT engine on the maintenance database does that job.

It also owns the app fixtures (`app_no_db`, `app_with_db`, `admin_app`) shared by
`test_api_health.py` and `test_api_auth.py`. Both configure the app with
**dependency overrides, never environment mutation**: `get_settings`, `get_engine`
and `get_sessionmaker` are all `lru_cache`d, so poking `os.environ` would either do
nothing or poison every later test in the session.
"""

import asyncio
import contextlib
import logging
import os
from collections.abc import AsyncIterator, Iterator
from pathlib import Path
from typing import Any

import httpx
import pytest
from alembic import command
from alembic.config import Config
from fastapi import FastAPI
from sqlalchemy import text
from sqlalchemy.exc import SQLAlchemyError
from sqlalchemy.ext.asyncio import (
    AsyncEngine,
    AsyncSession,
    async_sessionmaker,
    create_async_engine,
)

from fleetforge.api.deps import COOKIE_NAME
from fleetforge.api.main import create_app
from fleetforge.auth.hashing import hash_secret
from fleetforge.config import Settings, get_settings
from fleetforge.db.base import get_sessionmaker
from fleetforge.storage.objectstore import ObjectNotFound

REPO_ROOT = Path(__file__).resolve().parent.parent
TEST_DB_NAME = "fleetforge_test"
DEFAULT_DEV_URL = "postgresql+asyncpg://fleetforge:fleetforge@localhost:5433/fleetforge"

# The admin password the `admin_app` fixture is configured with. Hashed once at
# import: argon2 is ~40 ms a call and every auth test would otherwise pay it twice.
TEST_PASSWORD = "correct-horse-battery-staple"
TEST_PASSWORD_HASH = hash_secret(TEST_PASSWORD)


def database_url_for(db_name: str) -> str:
    """Return the configured dev/test URL with its database name replaced."""
    base = os.environ.get("TEST_DATABASE_URL") or os.environ.get("DATABASE_URL", DEFAULT_DEV_URL)
    head, _, _ = base.rpartition("/")
    return f"{head}/{db_name}"


TERMINATE_SQL = text(
    "SELECT pg_terminate_backend(pid) FROM pg_stat_activity "
    "WHERE datname = :db_name AND pid <> pg_backend_pid()"
)


async def drop_database(db_name: str, then_create: bool = False) -> None:
    """Drop `db_name` (optionally recreating it), evicting stragglers first.

    `DROP`/`CREATE DATABASE` cannot run inside a transaction and cannot take bind
    parameters, hence the AUTOCOMMIT engine and the quoted identifier. `db_name` is a
    module constant, never user input.
    """
    admin_engine = create_async_engine(
        database_url_for("postgres"), isolation_level="AUTOCOMMIT", pool_pre_ping=True
    )
    try:
        async with admin_engine.connect() as conn:
            await conn.execute(TERMINATE_SQL, {"db_name": db_name})
            await conn.exec_driver_sql(f'DROP DATABASE IF EXISTS "{db_name}"')
            if then_create:
                await conn.exec_driver_sql(f'CREATE DATABASE "{db_name}"')
    finally:
        await admin_engine.dispose()


async def recreate_database(db_name: str) -> None:
    """Drop and recreate `db_name`."""
    await drop_database(db_name, then_create=True)


def alembic_config() -> Config:
    """Alembic config pinned to the repo root, wherever pytest was invoked from."""
    cfg = Config(str(REPO_ROOT / "alembic.ini"))
    cfg.set_main_option("script_location", str(REPO_ROOT / "alembic"))
    return cfg


async def run_alembic(db_url: str, action: str = "upgrade", revision: str = "head") -> None:
    """Run an Alembic command against `db_url` in a worker thread.

    `alembic/env.py` calls `asyncio.run()`, which cannot be nested inside the running
    test loop — hence `to_thread`. `env.py` reads DATABASE_URL from the environment,
    so that is how the target database is selected.
    """
    runner = {"upgrade": command.upgrade, "downgrade": command.downgrade}[action]
    previous = os.environ.get("DATABASE_URL")
    os.environ["DATABASE_URL"] = db_url
    try:
        await asyncio.to_thread(runner, alembic_config(), revision)
    finally:
        if previous is None:
            os.environ.pop("DATABASE_URL", None)
        else:
            os.environ["DATABASE_URL"] = previous


async def run_alembic_check(db_url: str) -> None:
    """Run `alembic check` against `db_url`; raises AutogenerateDiffsDetected on drift."""
    previous = os.environ.get("DATABASE_URL")
    os.environ["DATABASE_URL"] = db_url
    try:
        await asyncio.to_thread(command.check, alembic_config())
    finally:
        if previous is None:
            os.environ.pop("DATABASE_URL", None)
        else:
            os.environ["DATABASE_URL"] = previous


@pytest.fixture(scope="session")
async def engine() -> AsyncIterator[AsyncEngine]:
    """Session-scoped engine bound to a freshly migrated `fleetforge_test`."""
    test_url = database_url_for(TEST_DB_NAME)
    try:
        await recreate_database(TEST_DB_NAME)
    except SQLAlchemyError as exc:  # pragma: no cover - environment problem, not a test failure
        pytest.exit(
            "Cannot reach PostgreSQL at "
            f"{database_url_for('postgres')}: {exc}\n"
            "Start the dev database first:  just db-up",
            returncode=1,
        )

    await run_alembic(test_url)

    test_engine = create_async_engine(test_url, pool_pre_ping=True)
    try:
        yield test_engine
    finally:
        await test_engine.dispose()
        await drop_database(TEST_DB_NAME)


@pytest.fixture
async def session(engine: AsyncEngine) -> AsyncIterator[AsyncSession]:
    """A session inside a transaction that is always rolled back.

    Tests never see each other's rows, and nothing needs cleaning up.
    """
    async with engine.connect() as connection:
        transaction = await connection.begin()
        async_session = AsyncSession(bind=connection, expire_on_commit=False)
        try:
            yield async_session
        finally:
            await async_session.close()
            if transaction.is_active:
                await transaction.rollback()


class _RecordCollector(logging.Handler):
    """Keeps every record it is handed. Levels are decided by the logger, not here."""

    def __init__(self) -> None:
        super().__init__(level=logging.NOTSET)
        self.records: list[logging.LogRecord] = []

    def emit(self, record: logging.LogRecord) -> None:
        self.records.append(record)


@contextlib.contextmanager
def capture_logs(name: str = "fleetforge") -> Iterator[list[logging.LogRecord]]:
    """Collect records emitted under `name`. **Use this instead of `caplog`.**

    Two things in this suite silently break `caplog`, and both of them turn an
    assertion like "the broker password is never logged" into a **vacuous pass**, which
    is worse than having no test:

    * `api/main.py::configure_logging` calls `logging.basicConfig(force=True)`, which
      removes every handler on the **root** logger — `caplog`'s included.
    * `alembic/env.py` calls `fileConfig(...)`, whose default is
      `disable_existing_loggers=True`. Running the migrations (the `engine` fixture
      does, once per session) therefore sets `disabled = True` on every `fleetforge.*`
      logger that has been imported by then, and they emit nothing for the rest of the
      run. Production is unaffected: the container migrates in a **separate**
      `alembic upgrade` process (`docker/entrypoint.sh`), not in-process.

    So this attaches to the package logger, lowers its level, and un-disables the
    subtree for the duration — restoring all three afterwards. Every assertion using it
    should also assert that *something* was captured.
    """
    logger = logging.getLogger(name)
    handler = _RecordCollector()
    previous_level = logger.level

    prefix = f"{name}."
    silenced = [
        existing
        for logger_name, existing in logging.Logger.manager.loggerDict.items()
        if isinstance(existing, logging.Logger)
        and (logger_name == name or logger_name.startswith(prefix))
        and existing.disabled
    ]

    logger.addHandler(handler)
    logger.setLevel(logging.DEBUG)
    for existing in silenced:
        existing.disabled = False
    try:
        yield handler.records
    finally:
        for existing in silenced:
            existing.disabled = True
        logger.setLevel(previous_level)
        logger.removeHandler(handler)


# ---------------------------------------------------------------------------
# App fixtures. In-process against the ASGI app — no uvicorn, no network.
# ---------------------------------------------------------------------------


def client_for(app: FastAPI, base_url: str = "http://testserver") -> httpx.AsyncClient:
    """An httpx client bound straight to the ASGI app.

    Pass `base_url="https://testserver"` for anything that must keep a cookie:
    `http.cookiejar` (which httpx uses) drops a `Secure` cookie on a plain-http
    origin. It does not model `localhost` as a secure context the way browsers do,
    so the fix is the test's URL scheme — never a weaker cookie.
    """
    return httpx.AsyncClient(transport=httpx.ASGITransport(app=app), base_url=base_url)


def settings_for_tests(**overrides: object) -> Settings:
    """A `Settings` built explicitly, not from the environment.

    The database URL is deliberately unusable: every app fixture overrides
    `get_sessionmaker`, so anything that reaches for this URL is a bug worth a loud
    connection error rather than a silent write to the developer's dev database.

    **Every object-store field is nulled**, because `Settings` still reads `.env` for
    anything not passed here and `.env.example` ships `S3_ENDPOINT_URL=…`. Without
    these, "no backend configured → 503" passes on a machine with no `.env` and fails
    on a developer's box — or, worse, the reverse. Same family of trap as `capture_logs`
    above.
    """
    values: dict[str, object] = {
        "database_url": "postgresql+asyncpg://unused:unused@127.0.0.1:1/unused",
        "admin_password_hash": TEST_PASSWORD_HASH,
        "object_store_backend": None,
        "s3_endpoint_url": None,
        "s3_bucket": None,
        "s3_access_key": None,
        "s3_secret_key": None,
        "s3_public_endpoint_url": None,
        "gcs_bucket": None,
        "gcs_credentials_file": None,
        "gcs_impersonate_service_account": None,
    }
    values.update(overrides)
    return Settings(**values)  # type: ignore[arg-type]


@pytest.fixture
def app_no_db() -> FastAPI:
    """The app with nothing overridden — usable without a database."""
    return create_app()


@pytest.fixture
def app_with_db(engine: AsyncEngine) -> FastAPI:
    """The app bound to the migrated test database.

    A dependency override, not an environment mutation: `get_settings` and
    `get_engine` are both `lru_cache`d, so poking `DATABASE_URL` into `os.environ`
    would either do nothing or poison every later test in the session.
    """
    app = create_app()
    sessionmaker = async_sessionmaker(engine, expire_on_commit=False)
    app.dependency_overrides[get_sessionmaker] = lambda: sessionmaker
    return app


@pytest.fixture
def admin_app(app_with_db: FastAPI) -> FastAPI:
    """`app_with_db` plus a known admin password (`TEST_PASSWORD`)."""
    settings = settings_for_tests()
    app_with_db.dependency_overrides[get_settings] = lambda: settings
    return app_with_db


async def login_admin(app: FastAPI, password: str = TEST_PASSWORD) -> str:
    """Log in against `app` and return the raw `ffa_` token from the `Set-Cookie`.

    Shared by every HTTP suite that needs a credential, so there is one login helper
    rather than one per test module. The client uses `https://testserver` because the
    session cookie is `Secure` — see `client_for`.
    """
    async with client_for(app, base_url="https://testserver") as client:
        response = await client.post("/v1/auth/login", json={"password": password})
    assert response.status_code == 200, response.text
    token = response.cookies[COOKIE_NAME]
    assert isinstance(token, str)
    return token


class MemoryObjectStore:
    """An in-memory `ObjectStore`: a dict, plus the contract's error behaviour.

    Shared by `test_blob_keys.py` (which only reads `puts`), `test_agent_publish.py` and
    `test_agent_catalog_store.py`, so there is one fake rather than three that drift. It
    implements the Protocol structurally — no base class, the same way the real adapters
    do — and its `get` raises `ObjectNotFound`, never returns `None`, because a fake that
    is more forgiving than the contract hides exactly the bug the contract exists to stop.

    `fail_with` makes the store refuse every verb: the named-fault path
    (`ObjectStoreError` → 503) has to be reachable without unplugging MinIO.
    """

    def __init__(self) -> None:
        self.objects: dict[str, bytes] = {}
        # (key, data, content_type, cache_control) per put, in order.
        self.puts: list[tuple[str, bytes, str, str | None]] = []
        self.gets: list[str] = []
        self.fail_with: Exception | None = None

    def _maybe_fail(self) -> None:
        if self.fail_with is not None:
            raise self.fail_with

    async def put(
        self,
        key: str,
        data: bytes,
        *,
        content_type: str = "application/octet-stream",
        cache_control: str | None = None,
    ) -> None:
        self._maybe_fail()
        self.puts.append((key, data, content_type, cache_control))
        self.objects[key] = data

    async def get(self, key: str) -> bytes:
        self._maybe_fail()
        self.gets.append(key)
        try:
            return self.objects[key]
        except KeyError as exc:
            raise ObjectNotFound(f"no object at {key}") from exc

    async def signed_url(self, key: str, *, ttl_s: int | None = None) -> str:
        self._maybe_fail()
        return f"https://memory.invalid/{key}?ttl={ttl_s}"

    async def delete(self, key: str) -> None:
        self._maybe_fail()
        self.objects.pop(key, None)


class FakeCommandPublisher:
    """An in-memory `CommandPublisher`: records what was published, or refuses. R1-be-2.

    Structural, like `MemoryObjectStore` — no base class, because the real adapter has
    none either. It records the **whole** payload so a test can assert the exact wire
    shape against `spec/device-protocol.md`, and `fail_with` makes the
    `CommandPublishError` → `failed` row → 503 path reachable with no broker running.
    """

    def __init__(self) -> None:
        # (device_id, payload) per publish, in order.
        self.published: list[tuple[str, dict[str, Any]]] = []
        self.fail_with: Exception | None = None

    async def publish(self, device_id: str, payload: dict[str, Any]) -> None:
        if self.fail_with is not None:
            raise self.fail_with
        self.published.append((device_id, payload))

    @property
    def last(self) -> dict[str, Any]:
        """The most recent payload; fails the test loudly if nothing was published."""
        assert self.published, "nothing was published"  # noqa: S101 - a test helper
        return self.published[-1][1]
